### ISSUE TITLE
使用阿里oss启动报错

### ISSUE THREAD

**Issue by mysens** [weimin96/oss-spring-starter#1]
<img width="1171" alt="image" src="https://github.com/user-attachments/assets/677b76bb-aeca-4bb2-9f6a-94d58bb66124">

似乎判断bucket是否存在有问题？

**Comment by weimin96** [comment]
抱歉，现在才看到
阿里云的配置可以参考如下
![image](https://github.com/user-attachments/assets/c7e9bc7e-39ba-4279-9110-4c723f06ba01)
