### ISSUE TITLE
无法实例化OssTemplate

### ISSUE THREAD

**Issue by anuouan** [weimin96/oss-spring-starter#6]
```java
Error creating bean with name 'ossTemplate' defined in class path resource [com/wiblog/oss/config/OssAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.wiblog.oss.service.OssTemplate]: Factory method 'ossTemplate' threw exception; nested exception is java.lang.NoClassDefFoundError: javax/servlet/ServletOutputStream
```
代码中是不是读取application.yml没有正确加载 ?

**Comment by weimin96** [comment]
javax/servlet/ServletOutputStream 在spring boot 3.x中已经弃用了，你的项目是不是spring boot 2.x并且引用了
```
<dependency>
    <groupId>io.github.weimin96</groupId>
    <artifactId>oss-spring-boot3-starter</artifactId>
</dependency>
```
spring boot2.x 项目可以查看分支[https://github.com/weimin96/oss-spring-boot-starter/tree/spring2](https://github.com/weimin96/oss-spring-boot-starter/tree/spring2)
```
<dependency>
    <groupId>io.github.weimin96</groupId>
    <artifactId>oss-spring-boot-starter</artifactId>
</dependency>
```

**Comment by anuouan** [comment]
> javax/servlet/ServletOutputStream 在spring boot 3.x中已经废弃了，你的项目不是spring boot 2.x并且引用了
> 
> ```
> <dependency>
>     <groupId>io.github.weimin96</groupId>
>     <artifactId>oss-spring-boot3-starter</artifactId>
> </dependency>
> ```
> 
> spring boot2.x 项目可以查看分支https://github.com/weimin96/oss-spring-boot-starter/tree/spring2
> 
> ```
> <dependency>
>     <groupId>io.github.weimin96</groupId>
>     <artifactId>oss-spring-boot-starter</artifactId>
> </dependency>
> ```

确实是我问题，已解决，谢谢！
